# kubernetes/client/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: your-client-service
spec:
  selector:
    app: your-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
